version: '2'
services:
 categoryservice-db:
   image: ${MYSQL_CATEGORY_DB_ADDR}
   volumes:
     - "./.data/db:/var/lib/categorydb"
   environment:
     MYSQL_ROOT_PASSWORD: bfd6f569f20bed7eaf811cbc1e
     MYSQL_DATABASE: ${MYSQL_CATEGORY_DB_DATABASE}
     MYSQL_USER: ${MYSQL_CATEGORY_DB_USER}
     MYSQL_PASSWORD: ${MYSQL_CATEGORY_DB_PASSWORD}
   ports:
     - "${MYSQL_CATEGORY_DB_PORT}:3306"

 categoryservice:
   depends_on:
     - categoryservice-db
   image: mavogel/categoryservice
   links:
     - categoryservice-db:${MYSQL_CATEGORY_DB_ADDR}
   environment:
     MYSQL_CATEGORY_DB_ADDR: ${MYSQL_CATEGORY_DB_ADDR}
     MYSQL_CATEGORY_DB_PORT: ${MYSQL_CATEGORY_DB_PORT}
     MYSQL_CATEGORY_DB_DATABASE: ${MYSQL_CATEGORY_DB_DATABASE}
     MYSQL_CATEGORY_DB_USER: ${MYSQL_CATEGORY_DB_USER}
     MYSQL_CATEGORY_DB_PASSWORD: ${MYSQL_CATEGORY_DB_PASSWORD}  
   ports:
     - "8080:8080"
