version: '2'
services:
 category-db:
   image: mysql:5.7.9
   volumes:
     - "./.data/db:/var/lib/categorydb"
   environment:
     MYSQL_ROOT_PASSWORD: bfd6f569f20bed7eaf811cbc1e
     MYSQL_DATABASE: ${MYSQL_CATEGORY_DB_DATABASE}
     MYSQL_USER: ${MYSQL_CATEGORY_DB_USER}
     MYSQL_PASSWORD: ${MYSQL_CATEGORY_DB_PASSWORD}
   ports:
     - "${MYSQL_CATEGORY_DB_PORT}:3306"

 categoryservice:
   depends_on:
     - category-db
   image: mavogel/categoryservice
   links:
     - category-db:${MYSQL_CATEGORY_DB_ADDR}
   ports:
     - "8080:8080"
