version: '2'
services:
 web-shop-db-image:
   image: mavogel/vis-web-shop-db-image
   volumes:
     - "./.data/db:/var/lib/mysql"
   environment:
     MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
     MYSQL_DATABASE: webshop
     MYSQL_USER: webshopuser
     MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
   ports:
     - "3306:3306"

 legacywebshop:
   depends_on:
     - web-shop-db-image
   image: mavogel/vis-legacywebshop
   links:
     - web-shop-db-image
   ports:
     - "8888:8080"
