version: '2'
services:
 webshop-db:
   image: web-shop-db-image
   volumes:
     - "./.data/db:/var/lib/mysql"
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
     MYSQL_DATABASE: ${MYSQL_WEBSHOP_DB_DATABASE}
     MYSQL_USER: ${MYSQL_WEBSHOP_DB_USER}
     MYSQL_PASSWORD: ${MYSQL_WEBSHOP_DB_PASSWORD}
   ports:
     - "${MYSQL_WEBSHOP_DB_PORT}:3306"

 categoryservice:
   depends_on:
     - webshop-db
   image: ${DOCKER_USER}/${DOCKER_PROJECT_IMAGE_PREFIX}-categoryservice
   links:
     - webshop-db:${MYSQL_WEBSHOP_DB_ADDR}
   restart: always
   environment:
     MYSQL_WEBSHOP_DB_ADDR: ${MYSQL_WEBSHOP_DB_ADDR}
     MYSQL_WEBSHOP_DB_PORT: ${MYSQL_WEBSHOP_DB_PORT}
     MYSQL_WEBSHOP_DB_DATABASE: ${MYSQL_WEBSHOP_DB_DATABASE}
     MYSQL_WEBSHOP_DB_USER: ${MYSQL_WEBSHOP_DB_USER}
     MYSQL_WEBSHOP_DB_PASSWORD: ${MYSQL_WEBSHOP_DB_PASSWORD}
   ports:
     - "8080:8080"

 productservice:
   depends_on:
     - webshop-db
   image: ${DOCKER_USER}/${DOCKER_PROJECT_IMAGE_PREFIX}-productservice
   links:
     - webshop-db:${MYSQL_WEBSHOP_DB_ADDR}
   restart: always
   environment:
     MYSQL_WEBSHOP_DB_ADDR: ${MYSQL_WEBSHOP_DB_ADDR}
     MYSQL_WEBSHOP_DB_PORT: ${MYSQL_WEBSHOP_DB_PORT}
     MYSQL_WEBSHOP_DB_DATABASE: ${MYSQL_WEBSHOP_DB_DATABASE}
     MYSQL_WEBSHOP_DB_USER: ${MYSQL_WEBSHOP_DB_USER}
     MYSQL_WEBSHOP_DB_PASSWORD: ${MYSQL_WEBSHOP_DB_PASSWORD}
   ports:
     - "8081:8080"

 userservice:
   depends_on:
     - webshop-db
   image: ${DOCKER_USER}/${DOCKER_PROJECT_IMAGE_PREFIX}-userservice
   links:
     - webshop-db:${MYSQL_WEBSHOP_DB_ADDR}
   restart: always
   environment:
     MYSQL_WEBSHOP_DB_ADDR: ${MYSQL_WEBSHOP_DB_ADDR}
     MYSQL_WEBSHOP_DB_PORT: ${MYSQL_WEBSHOP_DB_PORT}
     MYSQL_WEBSHOP_DB_DATABASE: ${MYSQL_WEBSHOP_DB_DATABASE}
     MYSQL_WEBSHOP_DB_USER: ${MYSQL_WEBSHOP_DB_USER}
     MYSQL_WEBSHOP_DB_PASSWORD: ${MYSQL_WEBSHOP_DB_PASSWORD}
   ports:
     - "8082:8080"

 categorycompositeservice:
   depends_on:
     - userservice
     - categoryservice
     - productservice
   image: ${DOCKER_USER}/${DOCKER_PROJECT_IMAGE_PREFIX}-categorycompositeservice
   links:
     - userservice
     - categoryservice
     - productservice
   restart: always
   ports:
     - "8083:8080"

 discovery:
   image: ${DOCKER_USER}/${DOCKER_PROJECT_IMAGE_PREFIX}-discovery
   restart: always
   ports:
     - "8761:8761"

 gateway:
   image: ${DOCKER_USER}/${DOCKER_PROJECT_IMAGE_PREFIX}-gateway
   restart: always
   ports:
     - "8088:8081"
