server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    fetch-registry: true
  instance:
    preferIpAddress: true
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
sidecar:
  port: 8000
ribbon:
  readTimeout: 10000
  eureka:
    enabled: true
# see: https://stackoverflow.com/questions/28904247/zuul-timing-out-in-long-ish-requests
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
zuul:
  ignoredServices: '*'
  host:
      connect-timeout-millis: 20000
      socket-timeout-millis: 20000
  routes:
    categorycomposite_category:
      path: /category/**
      serviceId: categorycomposite
      stripPrefix: false
      sensitiveHeaders:
    categorycomposite_product:
      path: /product/**
      serviceId: categorycomposite
      stripPrefix: false
      sensitiveHeaders:
    categorycomposite_user:
      path: /user/**
      serviceId: categorycomposite
      stripPrefix: false
      sensitiveHeaders: