server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
sidecar:
  port: 8000
ribbon:
  eureka:
    enabled: true
#zuul:
#  ignoredServices: '*'
#  host:
#      connect-timeout-millis: 20000
#      socket-timeout-millis: 20000
#
#  routes:
#    listservice:
#      path: /listservice/**
#      serviceId: listservice
#      stripPrefix: false
#      sensitiveHeaders:
#    modifyservice:
#      path: /modifyservice/**
#      serviceId: modifyservice
#      stripPrefix: false
#      sensitiveHeaders:
#    userservice:
#      path: /userservice/**
#      serviceId: userservice
#      stripPrefix: false
#      sensitiveHeaders: