server:
  port: 8080
spring:
  application:
    name: categorycomposite
    jackson:
        serialization:
          indent_output: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    fetch-registry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

# see: https://stackoverflow.com/questions/28904247/zuul-timing-out-in-long-ish-requests
ribbon:
  readTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000