spring:
  application:
    name: productservice
  profiles: container
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_WEBSHOP_DB_ADDR}:${MYSQL_WEBSHOP_DB_PORT}/${MYSQL_WEBSHOP_DB_DATABASE}?useSSL=false
    username: ${MYSQL_WEBSHOP_DB_USER}
    password: ${MYSQL_WEBSHOP_DB_PASSWORD}
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"